example_location: "examples"
api_groups:
  - "AdmissionRegistration"
  - "ApiExtensions"
  - "ApiRegistration"
  - "Apps"
  - "AuditRegistration"
  - "Authentication"
  - "Authorization"
  - "Autoscaling"
  - "Batch"
  - "Certificates"
  - "Coordination"
  - "Core"
  - "Discovery"
  - "Extensions"
  - "Meta"
  - "Networking"
  - "Node"
  - "Policy"
  - "Rbac"
  - "Scheduling"
  - "Settings"
  - "Storage"
resource_categories:
  - name: "Workloads APIs"
    include: "workloads"
    resources:
    - name: Pod
      version: v1
      group: core
      include: 
        definition: PodSpec
        file: "pod"
      categories:
        definition: PodSpec
        list:
        - name: Containers
          fields:
          - containers
          - initContainers
          - imagePullSecrets
          - enableServiceLinks
        - name: Volumes
          fields:
          - volumes
        - name: Scheduling
          fields:
          - nodeSelector
          - nodeName
          - affinity
          - tolerations
          - schedulerName
          - runtimeClassName
          - priorityClassName
          - priority
        - name: Lifecycle
          fields:
          - restartPolicy
          - terminationGracePeriodSeconds
          - activeDeadlineSeconds
          - readinessGates
        - name: Hostname and Name resolution
          fields:
          - hostname
          - subdomain
          - hostAliases
          - dnsConfig
          - dnsPolicy
        - name: Hosts namespaces
          fields:
          - hostNetwork
          - hostPID
          - hostIPC
          - shareProcessNamespace
        - name: Service account
          fields:
          - serviceAccountName
          - automountServiceAccountToken
        - name: Security context
          fields:
          - securityContext
        - name: Alpha level
          fields:
          - ephemeralContainers
          - overhead
          - preemptionPolicy
          - topologySpreadConstraints
        - name: Deprecated
          fields:
          - serviceAccount
    - name: Container
      version: v1
      group: core
      include:
        file: "container"
      categories:
        list:
        - name: Image
          fields:
          - image
          - imagePullPolicy
        - name: Entrypoint
          fields:
          - command
          - args
          - workingDir
        - name: Ports
          fields:
          - ports
        - name: Environment variables
          fields:
          - env
          - envFrom
        - name: Volumes
          fields:
          - volumeMounts
          - volumeDevices
        - name: Name
          fields:
          - name
        - name: Resources
          fields:
          - resources
        - name: Lifecycle
          fields:
          - lifecycle
          - terminationMessagePath
          - terminationMessagePolicy
          - livenessProbe
          - readinessProbe
        - name: Security Context
          fields:
          - securityContext
        - name: Debugging
          fields:
          - stdin
          - stdinOnce
          - tty
        - name: Alpha level
          fields:
          - startupProbe
    - name: ReplicaSet
      version: v1
      group: apps
      include:
        definition: ReplicaSetSpec
        file: "replicaset"
      categories:
        definition: ReplicaSetSpec
        list:
        - fields:
          - replicas
          - selector
          - template
          - minReadySeconds
    - name: Deployment
      version: v1
      group: apps
    - name: StatefulSet
      version: v1
      group: apps
    - name: Job
      version: v1
      group: batch
    - name: CronJob
      version: v1beta1
      group: batch
    - name: DaemonSet
      version: v1
      group: apps
  - name: "Service APIs"
    include: "servicediscovery"
    resources:
    - name: Service
      version: v1
      group: core
    - name: Endpoints
      version: v1
      group: core
    - name: EndpointSlice
      version: v1alpha1
      group: discovery
    - name: Ingress
      version: v1beta1
      group: networking
  - name: "Config and Storage APIs"
    include: "config"
    resources:
    - name: ConfigMap
      version: v1
      group: core
    - name: Secret
      version: v1
      group: core
    - name: Volume
      version: v1
      group: core
    - name: PersistentVolumeClaim
      version: v1
      group: core
      description_note: "A <a href=\"#persistentvolume-v1-core\">PersistentVolume</a> must be allocated in the cluster to use this."
    - name: StorageClass
      version: v1
      group: storage
    - name: VolumeAttachment
      version: v1
      group: storage
    - name: CSIDriver
      version: v1beta1
      group: storage
    - name: CSINode
      version: v1beta1
      group: storage
  - name: "Metadata APIs"
    include: "meta"
    resources:
    - name: ControllerRevision
      version: v1
      group: apps
    - name: CustomResourceDefinition
      version: v1
      group: apiextensions
    - name: Event
      version: v1
      group: core
    - name: LimitRange
      version: v1
      group: core
    - name: HorizontalPodAutoscaler
      version: v1
      group: autoscaling
    - name: MutatingWebhookConfiguration
      version: v1
      group: admissionregistration
    - name: ValidatingWebhookConfiguration
      version: v1
      group: admissionregistration
    - name: PodTemplate
      version: v1
      group: core
    - name: PodDisruptionBudget
      version: v1beta1
      group: policy
    - name: PriorityClass
      version: v1
      group: scheduling
    - name: PodPreset
      version: v1alpha1
      group: settings
      description_warning: "Alpha objects should not be used in production and may not be compatible with future versions of the resource type."
    - name: PodSecurityPolicy
      version: v1beta1
      group: policy
  - name: "Cluster APIs"
    include: "cluster"
    resources:
    - name: APIService
      version: v1
      group: apiregistration
    - name: AuditSink
      version: v1alpha1
      group: auditregistration
    - name: Binding
      version: v1
      group: core
    - name: CertificateSigningRequest
      version: v1beta1
      group: certificates
    - name: ClusterRole
      version: v1
      group: rbac
    - name: ClusterRoleBinding
      version: v1
      group: rbac
    - name: ComponentStatus
      version: v1
      group: core
    - name: Lease
      version: v1
      group: coordination
    - name: LocalSubjectAccessReview
      version: v1
      group: authorization
    - name: Namespace
      version: v1
      group: core
    - name: Node
      version: v1
      group: core
    - name: PersistentVolume
      version: v1
      group: core
      description_note: "These are assigned to <a href=\"#pod-v1-core\">Pods</a> using <a href=\"#persistentvolumeclaim-v1-core\">PersistentVolumeClaims</a>."
    - name: ResourceQuota
      version: v1
      group: core
    - name: Role
      version: v1
      group: rbac
    - name: RoleBinding
      version: v1
      group: rbac
    - name: RuntimeClass
      version: v1beta1
      group: node
    - name: SelfSubjectAccessReview
      version: v1
      group: authorization
    - name: SelfSubjectRulesReview
      version: v1
      group: authorization
    - name: ServiceAccount
      version: v1
      group: core
    - name: SubjectAccessReview
      version: v1
      group: authorization
    - name: TokenRequest
      version: v1
      group: authentication
    - name: TokenReview
      version: v1
      group: authentication
    - name: NetworkPolicy
      version: v1
      group: networking
operation_categories:
  - name: "Proxy Operations"
    operation_types:
    - name: Create Connect Portforward
      match: connect${group}${version}Post(Namespaced)?${resource}Portforward
    - name: Create Connect Proxy
      match: connect${group}${version}Post(Namespaced)?${resource}Proxy
    - name: Create Connect Proxy Path
      match: connect${group}${version}Post(Namespaced)?${resource}ProxyWithPath
    - name: Create Proxy
      match: proxy${group}${version}POST(Namespaced)?${resource}
    - name: Create Proxy Path
      match: proxy${group}${version}POST(Namespaced)?${resource}WithPath
    - name: Delete Connect Proxy
      match: connect${group}${version}Delete(Namespaced)?${resource}Proxy
    - name: Delete Connect Proxy Path
      match: connect${group}${version}Delete(Namespaced)?${resource}ProxyWithPath
    - name: Delete Proxy
      match: proxy${group}${version}DELETE(Namespaced)?${resource}
    - name: Delete Proxy Path
      match: proxy${group}${version}DELETE(Namespaced)?${resource}WithPath
    - name: Get Connect Portforward
      match: connect${group}${version}Get(Namespaced)?${resource}Portforward
    - name: Get Connect Proxy
      match: connect${group}${version}Get(Namespaced)?${resource}Proxy
    - name: Get Connect Proxy Path
      match: connect${group}${version}Get(Namespaced)?${resource}ProxyWithPath
    - name: Get Proxy
      match: proxy${group}${version}GET(Namespaced)?${resource}
    - name: Get Proxy Path
      match: proxy${group}${version}GET(Namespaced)?${resource}WithPath
    - name: Head Connect Proxy
      match: connect${group}${version}Head(Namespaced)?${resource}Proxy
    - name: Head Connect Proxy Path
      match: connect${group}${version}Head(Namespaced)?${resource}ProxyWithPath
    - name: Replace Connect Proxy
      match: connect${group}${version}Put(Namespaced)?${resource}Proxy
    - name: Replace Connect Proxy Path
      match: connect${group}${version}Put(Namespaced)?${resource}ProxyWithPath
    - name: Replace Proxy
      match: proxy${group}${version}PUT(Namespaced)?${resource}
    - name: Replace Proxy Path
      match: proxy${group}${version}PUT(Namespaced)?${resource}WithPath
  - name: "Misc Operations"
    default: true
    operation_types:
    - name: Read Scale
      match: read${group}${version}(Namespaced)?${resource}Scale
    - name: Replace Scale
      match: replace${group}${version}(Namespaced)?${resource}Scale
    - name: Patch Scale
      match: patch${group}${version}(Namespaced)?${resource}Scale
    - name: Rollback
      match: create${group}${version}(Namespaced)?${resource}Rollback
    - name: Read Log
      match: read${group}${version}(Namespaced)?${resource}Log
